wifi_ssid: ENC[AES256_GCM,data:OcmTWkdz,iv:jIzLKTeRy168EqZM4hawnz1UCvvrbcSD+cMqGYQvu7Y=,tag:nd5xq4j6Y5xczER3F/vDlQ==,type:str]
wifi_password: ENC[AES256_GCM,data:MyGQpFi5bUMTzFLCgrd1,iv:RkzXgwdChCkX9BTuJm/nNR796/rJ3KPGoY+1dwT8BSY=,tag:T5NZiOEn8O7FeAm6dpMfhQ==,type:str]
kitchenlight_fallback_wifi_password: ENC[AES256_GCM,data:ljeJlQiXBSv1x95EJOlfrQ==,iv:xO89KeXAwhnuln8GLjcP23jC4wAes4fD7FQOhn12JU4=,tag:tvp6jjt632oSVSZuevKS0Q==,type:str]
kitchenlight_api_encryption_key: ENC[AES256_GCM,data:aTXqjZPL1ZpCeoWHTlU76DXVJoZBZ/StSOH2VGviizZIGvi6T/chxaB1xno=,iv:dYEfIjVwz4Q8n4MvqyOOBvErrEHLubMsCsqJT0hOLNQ=,tag:0VuvrMLxy2w3STsXtPJPBg==,type:str]
kitchenlight_ota_password: ENC[AES256_GCM,data:NYvCe/zLodXo4mMecoGCIolvgoJ5k85Cwtngqaikado=,iv:WLevfsOrF2IOAWQ7v4O2OLpnNtwN+AUHp9eLuW6kJeU=,tag:gjvvaf80ZBnOfmXao53E5g==,type:str]
bedroomlight_fallback_wifi_password: ENC[AES256_GCM,data:uB7ErLXJDN4uhkMb8BBB/Q==,iv:Vq/RQQcWPAuFAOMEWd+oHllxjXV0EQw0kImBgqsI5nY=,tag:bELoGBuzkTmMgk6ZoJrdGA==,type:str]
bedroomlight_api_encryption_key: ENC[AES256_GCM,data:n8FmacDdR5fUqjEyR0r3R+ODDPt+buIzTocuOcxBMCd38EeRrkPUsCQNhFs=,iv:lWfl3UypiyiucZDnKRnjCCahrBiEm7z6G+VQQHqqAIc=,tag:sFlHkV5ehG4D9O9RuDFZrA==,type:str]
bedroomlight_ota_password: ENC[AES256_GCM,data:kVvS0ovLT8x4Q+ZpSLHl9hy/agYCP+Rwu25oRTWf9cs=,iv:3650SkoW9bP8fvNAgmkwTh32+E8XX/0yYnw/2LKTtqQ=,tag:KQoqmCp7HgJXRidLIyP4WA==,type:str]
btproxy_fallback_wifi_password: ENC[AES256_GCM,data:o1uTP8Wu+1MZBgnE1+EfJg==,iv:JXJK8c2RSq0gJhdaZxBUWi9kOaeIoVswdMeKKC+VHXQ=,tag:g+pPaXetR117CrzErIUNFA==,type:str]
btproxy_api_encryption_key: ENC[AES256_GCM,data:SNlL1syCxU3yCb4CFyL8m/GeABTipYDAl4Ptdo8VJfeNmd9ZnQ6e5IlCt4U=,iv:iQlKQS25u49WPchn+9nPcFuK4oj2yT7fLPj5EZgpLLU=,tag:6Zf50kc7a/cuzUtfefBXxg==,type:str]
btproxy_ota_password: ENC[AES256_GCM,data:8jGrNwpBgu3p/wyklH5KNxIdh7FISPaKOHERcdr1qgM=,iv:0WKAL46rcjwhjkg1eI72PFirbIbGGPXxABDzpSzBG+w=,tag:29zd+FLpVHDsZhBw9T17hA==,type:str]
sops:
    age:
        - recipient: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDacshL0MKcPH/C0S7/ybYcd7+643Lo6X9VjAkwdgOCw3FKYWr20qKCHd0hPFXcYixt86aNuF2McNRae5h+dlPwPWIuJTt987gnp25IQlsWBeIiS1tDZI1lZcVu+Yj7BQMmp8uXkyP4KqjX9zaa3FmXv4MeWz/41rRYj72A1ZlsF1H/SxZ7uQX27XuhV5nOvsH2yAbXKexDwcvcR/lrxQcYH9el3QDt6x229lqn9piuSSl/LYAN81jxd/4a2Pwrnqeqca+HC9xY6LF6NW64E2RkZMMTbsaFo8E4FFLnTzcYgP1+EKypPiphMhvCJQLOo3crcxMpv9eOGvgGh8iMdak3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1yc2EgSlNxSmd3ClNnOUVWSndN
            Wk96MlNIREtJYlZxVFlGSi9ENFJTblFNcjNsemF1MGNrYjgrODBTS2ptdzlnWms5
            SWh5VUVGdzMKek9Ib2xmNnRZZFdIdXB1ZHF5dHhNUXRmbDRIZm42c1lXc3pDWVFs
            SHdIS1NSQ09DZTIwZG9JeFZpTmpNTXg5bQpxRWpZVGdXNnB1ZUFCdFZNRytPd21C
            TXFxb0Q1OGF0SzBvS2tveUtRNGxmWGM3L0ptNVZqanFIdnNDU2trK3g2CjRRRWhn
            VW1haFZMSWJKLzFTNzM1Y3VTTlRHd1NTSDg2bFRPbG8rNkhqUGVKRWJia2lDWmU2
            R2ZoaWJRYjFhQUkKVTBmQTJBRmN5cFdVUjVFZGdTMWI5VjBKNVhNSU5KRThhNWY0
            b0RPY3JxbEZlVVdZdXFzZW1DL0xmNlNkNVVKYQpjS1BEazNMZmdLNW9qYy9adFlJ
            TytnCi0tLSBHUVVnTlRoRnNuUnRqdGtBdWpDNk1uZjVaS3VuZ01zckxzTmY0dWp1
            RkZVCv9JLne8STctzg10HddqYlWsV3g3sbM4USeu4c/EwU9sLKOkYEc+e2sjFHGK
            a/ohWFZ/sS2dVznVXXK7ebzkKHc=
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDHPnrZgImCAprHnZQaIyn6Wvvl+YDEjHmm0B8F/TVz57G6E7fHD/Cc8VJ571j1sQ/OeJhSWGm94itmEBBJNx8uoKcVtXvd+7Uow+Ui45KpEGCuMAB+3PdZd6+yzr6yTXr121+//XYAn0bYhAmyijVSMxBZ5gwohmrSg+P2uArhvmuEmn2r5kJ5KCb1tyj2713bhVm/4bFs+q+fHcKRG/0/CyfOPFn8wGfKpjvmmAc1knbzn6zzLOn2tjhA4Y2KEnJuU13ZLvqJLBHXp50LwA0kRDD2irX+6ZJD5KY/JpbzVX5vdgSXUbwAEGeecnU5o7KgXWb61YetRJhi8vu6Q0bxSoG7l1q2XFo8n9mV3TBofFgn4F+nudS9iQ7Cl6To7hi3/0zHnE4M4PVt7idC4BcLyEwGp3rwPApjiuYO7Io3oFTYYv6OORDq788s+FHPDKoHnw2JY/qcEZYQNx9+iIeJhMpBvm2+g7Ysn2NyPoFsB6qg/ZF1TnXdu07t6pngp1E=
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1yc2EgR3RpTjdnCnUzNG01OStm
            NkJ3S3VSS241bW4wU1A2TDZGYW5ralFVVVY5NFdvaldsWDN1azlJejdrdmN4d3Q4
            c2puVU1HeFgKNkZSd2wyaFNBMTlvMkhvODgxYnp3YUVvZDNGb0dPZWx3clFCalJ6
            Rk1UWHFRTmhYNW1CZWwxcXZRZldUMVFEOApnMGRIT3JSbllPNHprdHExRHlCOUda
            UHMvakRyVGMrcncrOGVWYWszZ3Nrd0psb1FTMkxTd1MvQ3BmVjNnRmFyCnBkY1Aw
            cTd6WStaMk5jbHZ3eW10a21rUnI3aC9UYy9ZSS9ERE9FR0NkY213MXNOS0hCWFJz
            ZXIxSVZTcWVaQisKeXhFWFhxdVlTNzBuUThnK2lvMVRwMUpQR05jdlQ4VS9GR1VZ
            N3lkRURwQ21DMSthSW43bGZ2dG5VcXo1ZHJXNwpNVi9GNnAxa2RjRkJBK3lmVVFv
            bS9IVDUxaG82L2FNcjFuTmdJS1Vkbk9id3hEcXhRTW15TTl5VmM2T2hOa0V6ClRp
            NU9ubnphd1FLNzFrMFhuMG5vak5WcGdVUHdXT1JadWJoSEhpMjRZVUJSN3crR25k
            T0xHQklzZW5sL3grVnkKZlV1YzBEZUxqY01vWDdOR0NHcHg1RFJQaVhhV0tYMWVx
            c1RCRmw4UXpmcVF3RS9WT09ybVpxdHBFSjNUZEprcAoKLS0tIFlDM3A3Wms3YlpC
            Qi90VG9LaTZXMXkwd2JGelpMQitBMFpPTUZUeWpiZmcKayHQ2BMcfv42XstXEtwL
            A77PI6LnNET/VMgquTcmlrWF5g+TVwpp/27N/Z8QXaK5SA0J7CRL4DgwSmJOKd1c
            Dg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-07T19:56:55Z"
    mac: ENC[AES256_GCM,data:uWxU9+Bs053YJPW1tJdIetQT6rGaGhqNCtmB9F41tFQO+Af9ebBlW6Sbyfvnn0U2L7K8Nc9vCZJXoAcy2pC7mMHVdgChXJxEsO/pRhNsVDmIIrnxoXU4Dl/zDFI4z5qjhIkMPdDwagHqhAXPw9TWkoKBr7WMaqDd5Tjgy0QLvIg=,iv:Il4Vif4dtpsBlgD42g7sxDNcLZNL4UG6Msi6YWiA50Q=,tag:bVCUznkEwCeyLtBfEgOyLA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
