name: Update nixpkgs every friday

on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"

jobs:
  trigger_update:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - run: |
          gh workflow run update_flake.yml \
            --repo ${{ github.repository }} \
            --ref master \
            -f input="nixpkgs"
